export type {
  VeepooDevice,
  ConnectionStatus,
  ConnectionResult,
  ScanOptions,
  ScanResult,
  ConnectOptions,
  DeviceTimeSetting,
  BluetoothState,
  BluetoothAuthorization,
  PermissionStatus,
  PermissionsResult,
  BluetoothStatus,
  PasswordStatus,
  PasswordData,
} from './connection';

export type {
  FunctionStatus,
  DeviceFunctionPackage1,
  DeviceFunctionPackage2,
  DeviceFunctionPackage3,
  DeviceFunctionPackage4,
  DeviceFunctionPackage5,
  DeviceFunctions,
  DeviceVersion,
  ChargeState,
  BatteryInfo,
  Sex,
  PersonalInfo,
  SocialMsgData,
  CustomSettingData,
  DeviceAlarm,
  HeartRateAlarm,
  FindDevicePhase,
  ScreenLightSettings,
  ScreenLightDuration,
  SedentaryReminderSettings,
  WristFlipWakeSettings,
  WomenHealthBabySex,
  WomenHealthSettings,
  WomenHealthStatus,
  WatchFaceDialType,
  WatchFaceStyle,
  WatchFaceStyleSettings,
  WeatherUnit,
  WeatherSettings,
  WeatherHourlyForecast,
  WeatherDailyForecast,
  WeatherData,
  DeviceData,
  DeviceContact,
  NewDeviceContact,
  SosCallTimesSettings,
  CameraShutterStatus,
  MusicData,
  MusicRemoteCommand,
  GPSAndTimezoneData,
  DeviceBTState,
  DeviceBTStatus,
  HealthReminderType,
  HealthReminder,
  Spo2Alarm,
  DeviceSwitchType,
  DeviceSwitches,
} from './device';

export type {
  HeartRateData,
  BloodPressureData,
  BloodOxygenData,
  TemperatureData,
  StressData,
  BloodGlucoseData,
  SleepDataItem,
  SleepData,
  DailyHealthData,
  SportStepData,
  DaySummaryData,
  OriginData,
  HalfHourData,
  Spo2OriginData,
  ExerciseMinuteData,
  ExerciseSession,
  SleepMinuteState,
  SleepMinutePoint,
  AccurateSleepSession,
  StoredTemperatureData,
  StoredBloodGlucoseData,
  StoredHrvData,
  StoredEcgData,
  StoredBodyCompositionData,
} from './health-data';

export type {
  TestState,
  HeartRateTestResult,
  BloodPressureTestResult,
  BloodOxygenTestResult,
  TemperatureTestResult,
  BloodGlucoseTestResult,
  HrvTestResult,
  EcgTestOptions,
  EcgTestResult,
  FatigueTestResult,
  BreathingTestResult,
  BodyCompositionMetrics,
  BodyCompositionTestResult,
  BloodAnalysisValues,
  BloodAnalysisTestResult,
  GsrTestResult,
  PttState,
  PttTestResult,
  ReadState,
  ReadOriginProgress,
} from './health-tests';
export { RealtimeTest } from './health-tests';
export type { RealtimeTestModality } from './health-tests';

export type {
  AutoMeasureSetting,
  Language,
  TemperatureUnit,
  DistanceUnit,
  TimeFormat,
  BloodGlucoseUnit,
  SkinTone,
  CustomSettings,
  ApneaRemindSettings,
  OperationStatus,
  SportMode,
  SportModeStatus,
  BloodGlucoseRiskConfig,
  WorldClockEntry,
} from './settings';
export { SPORT_MODE_ORDINALS } from './settings';

export type {
  VeepooEvent,
  VeepooEventPayload,
  FirmwareDfuState,
  FirmwareDfuProgress,
} from './events';

export type { VeepooErrorCode, VeepooError, LogLevel, LogScope, LogEntry } from './errors';
