package expo.modules.veepoo

import expo.modules.kotlin.modules.ModuleDefinitionBuilder

// 事件导出
fun ModuleDefinitionBuilder.defineEvents() {
  Events(
    DEVICE_FOUND,
    DEVICE_CONNECTED,
    DEVICE_DISCONNECTED,
    DEVICE_CONNECT_STATUS,
    CONNECTION_STATUS_CHANGED,
    DEVICE_READY,
    BLUETOOTH_STATE_CHANGED,
    DEVICE_FUNCTION,
    DEVICE_VERSION,
    PASSWORD_DATA,
    BATTERY_DATA,
    SOCIAL_MSG_DATA,
    HEART_RATE_TEST_RESULT,
    BLOOD_PRESSURE_TEST_RESULT,
    BLOOD_OXYGEN_TEST_RESULT,
    TEMPERATURE_TEST_RESULT,
    STRESS_DATA,
    BLOOD_GLUCOSE_DATA,
    HRV_TEST_RESULT,
    ECG_TEST_RESULT,
    FATIGUE_TEST_RESULT,
    BREATHING_TEST_RESULT,
    SLEEP_DATA,
    SPORT_STEP_DATA,
    READ_ORIGIN_PROGRESS,
    READ_ORIGIN_COMPLETE,
    ORIGIN_FIVE_MINUTE_DATA,
    ORIGIN_HALF_HOUR_DATA,
    ORIGIN_SPO2_DATA,
    ALARM_DATA,
    FIND_DEVICE_STATE,
    FIRMWARE_DFU_PROGRESS,
    ERROR
  )
}
