package expo.modules.veepoo

// 日志标签
const val TAG = "VeepooSDKModule"

// 事件名称常量
const val DEVICE_FOUND = "deviceFound"
const val DEVICE_CONNECTED = "deviceConnected"
const val DEVICE_DISCONNECTED = "deviceDisconnected"
const val DEVICE_CONNECT_STATUS = "deviceConnectStatus"
const val CONNECTION_STATUS_CHANGED = "connectionStatusChanged"
const val DEVICE_READY = "deviceReady"
const val BLUETOOTH_STATE_CHANGED = "bluetoothStateChanged"
const val DEVICE_FUNCTION = "deviceFunction"
const val DEVICE_VERSION = "deviceVersion"
const val PASSWORD_DATA = "passwordData"
const val HEART_RATE_TEST_RESULT = "heartRateTestResult"
const val BLOOD_PRESSURE_TEST_RESULT = "bloodPressureTestResult"
const val BLOOD_OXYGEN_TEST_RESULT = "bloodOxygenTestResult"
const val TEMPERATURE_TEST_RESULT = "temperatureTestResult"
const val STRESS_DATA = "stressData"
const val BLOOD_GLUCOSE_DATA = "bloodGlucoseData"
const val HRV_TEST_RESULT = "hrvTestResult"
const val ECG_TEST_RESULT = "ecgTestResult"
const val FATIGUE_TEST_RESULT = "fatigueTestResult"
const val BREATHING_TEST_RESULT = "breathingTestResult"
const val READ_ORIGIN_PROGRESS = "readOriginProgress"
const val READ_ORIGIN_COMPLETE = "readOriginComplete"
const val ORIGIN_HALF_HOUR_DATA = "originHalfHourData"
const val ORIGIN_FIVE_MINUTE_DATA = "originFiveMinuteData"
const val ORIGIN_SPO2_DATA = "originSpo2Data"
const val SLEEP_DATA = "sleepData"
const val SPORT_STEP_DATA = "sportStepData"
const val BATTERY_DATA = "batteryData"
const val SOCIAL_MSG_DATA = "socialMsgData"
const val ALARM_DATA = "alarmData"
const val FIND_DEVICE_STATE = "findDeviceState"
const val FIRMWARE_DFU_PROGRESS = "firmwareDfuProgress"
const val ERROR = "error"
