import { passthrough, wrapInner, type PartialEventNormalizers } from '@/bridge/event-envelope';
import {
  normalizeBloodAnalysisTestResult,
  normalizeBloodGlucoseData,
  normalizeBloodOxygenTestResult,
  normalizeBloodPressureTestResult,
  normalizeBodyCompositionTestResult,
  normalizeBreathingTestResult,
  normalizeEcgTestResult,
  normalizeFatigueTestResult,
  normalizeGsrTestResult,
  normalizeHeartRateTestResult,
  normalizeHrvTestResult,
  normalizePttTestResult,
  normalizeStressData,
  normalizeTemperatureTestResult,
} from './normalizers';

export const EVENT_NORMALIZERS = {
  heart_rate_test_result: wrapInner('result', normalizeHeartRateTestResult),
  blood_pressure_test_result: wrapInner('result', normalizeBloodPressureTestResult),
  blood_oxygen_test_result: wrapInner('result', normalizeBloodOxygenTestResult),
  temperature_test_result: wrapInner('result', normalizeTemperatureTestResult),
  stress_data: wrapInner('data', normalizeStressData),
  blood_glucose_data: wrapInner('data', normalizeBloodGlucoseData),
  hrv_test_result: wrapInner('result', normalizeHrvTestResult),
  ecg_test_result: wrapInner('result', normalizeEcgTestResult),
  fatigue_test_result: wrapInner('result', normalizeFatigueTestResult),
  breathing_test_result: wrapInner('result', normalizeBreathingTestResult),
  body_composition_test_result: wrapInner('result', normalizeBodyCompositionTestResult),
  blood_analysis_test_result: wrapInner('result', normalizeBloodAnalysisTestResult),
  gsr_test_result: wrapInner('result', normalizeGsrTestResult),
  ptt_test_result: wrapInner('result', normalizePttTestResult),
  ptt_state_changed: passthrough<'ptt_state_changed'>(),
} satisfies PartialEventNormalizers;
