export { default } from './VeepooSDK.js';
export { default as VeepooSDK } from './VeepooSDK.js';

export type {
  VeepooDevice,
  ConnectionStatus,
  ConnectionResult,
  ScanOptions,
  ScanResult,
  ConnectOptions,
  DeviceTimeSetting,
  BluetoothState,
  BluetoothAuthorization,
  BluetoothStatus,
  PasswordStatus,
  PasswordData,
  FunctionStatus,
  DeviceFunctionPackage1,
  DeviceFunctionPackage2,
  DeviceFunctionPackage3,
  DeviceFunctionPackage4,
  DeviceFunctionPackage5,
  DeviceFunctions,
  DeviceVersion,
  ChargeState,
  BatteryInfo,
  Sex,
  PersonalInfo,
  HeartRateData,
  BloodPressureData,
  BloodOxygenData,
  TemperatureData,
  StressData,
  BloodGlucoseData,
  SleepDataItem,
  SleepData,
  DailyHealthData,
  SportStepData,
  DaySummaryData,
  OriginData,
  HalfHourData,
  Spo2OriginData,
  TestState,
  HeartRateTestResult,
  BloodPressureTestResult,
  BloodOxygenTestResult,
  TemperatureTestResult,
  BloodGlucoseTestResult,
  HrvTestResult,
  EcgTestOptions,
  EcgTestResult,
  FatigueTestResult,
  BreathingTestResult,
  BodyCompositionMetrics,
  BodyCompositionTestResult,
  ReadState,
  ReadOriginProgress,
  AutoMeasureSetting,
  Language,
  SocialMsgData,
  CustomSettingData,
  VeepooErrorCode,
  VeepooError,
  LogLevel,
  LogScope,
  LogEntry,
  VeepooEvent,
  VeepooEventPayload,
  FirmwareDfuState,
  FirmwareDfuProgress,
  OperationStatus,
  TemperatureUnit,
  DistanceUnit,
  TimeFormat,
  BloodGlucoseUnit,
  DeviceAlarm,
  HeartRateAlarm,
  FindDevicePhase,
  ScreenLightSettings,
  ScreenLightDuration,
  SedentaryReminderSettings,
  WristFlipWakeSettings,
  WomenHealthBabySex,
  WomenHealthSettings,
  WomenHealthStatus,
  WatchFaceDialType,
  WatchFaceStyle,
  WatchFaceStyleSettings,
  WeatherUnit,
  WeatherSettings,
  WeatherHourlyForecast,
  WeatherDailyForecast,
  WeatherData,
  DeviceData,
  PermissionsResult,
  PermissionStatus,
  CameraShutterStatus,
  MusicData,
  MusicRemoteCommand,
  GPSAndTimezoneData,
  DeviceBTState,
  DeviceBTStatus,
} from './types/index.js';
export { RealtimeTest } from './types/index.js';
export type { RealtimeTestModality } from './types/index.js';

export type { VeepooSDKModuleInterface, LogListener } from './VeepooSDKModule.js';

export { mapNativeRejection, isVeepooErrorShape } from './errors/map-native-rejection.js';
export type { MapNativeRejectionContext } from './errors/map-native-rejection.js';

export {
  VeepooSDKProvider,
  useVeepooSDK,
  useSDKState,
  useIsConnected,
  useIsSessionReady,
  useIsScanning,
  useConnectedDeviceId,
  useSDKInitialized,
} from './react/index.js';
export type { SDKStateSnapshot } from './react/index.js';

export {
  runSessionBaseline,
  attachSessionBaseline,
} from './session/index.js';
export type {
  SessionBaselineConfig,
  SessionBaselineResult,
  AttachSessionBaselineConfig,
  SessionBaselineHandle,
} from './session/index.js';
